### ISSUE TITLE
Upgrade planner doesn't uninstall the pole

### ISSUE THREAD

**Issue by LeonSkills** [Scarabytes/FactorioRealisticElectricTrains#18]
Currently working on a mod that sometimes marks a `rail-signal` and `rail-chain-signal` for upgrade.  

I noticed some incompatibilities with RET, and noticed the same happened with a regular upgrade planner  

How to reproduce:   

* Place one of the ret-poles  
* Create an upgrade planner with `from` to the newly placed pole, and `to` any of the six possible entities    
* Mark the pole for upgrade  
* Have bots replace the pole  
* Mine the pole  

Bots will fly to replace the pole, but the unminable "overhead line wire holder" remains.  
It's not immediately visible, you'd have to remove the pole again before you see the old one.   

It's also possible to upgrade a pole to itself (well, a `*-pole-base` to a `*-pole-placer`) 

While we are at it, any reason why the `fast_replaceable_group` of your bases aren't "rail-signal"? I can't mark them for upgrade to regular signals or vice versa, which might be useful.

**Comment by robot256** [comment]
Looking at the code, RET currently handles the following events for removing a pole:

		defines.events.on_entity_died,
		defines.events.on_pre_player_mined_item,
		defines.events.on_robot_pre_mined,
		defines.events.script_raised_destroy
	
Can you repeat your test with Creative Mod installed and have it display all the events that trigger?  If one of those is not triggering during an upgrade (or not triggering at the right time), that might cause the problem.

**Comment by LeonSkills** [comment]
@robot256 
None of these are triggered on upgrade, no  
```lua
defines.events.on_robot_mined_entity
defines.events.on_robot_built_entity
defines.events.on_robot_mined
```
(in that order)
are called

**Comment by robot256** [comment]
It looks like just adding on_robot_mined_entity to the list in addition to on_robot_pre_mined works okay too.

The bigger problem is that it appears to be impossible to properly configure an upgrade planner to replace diagonal poles with diagonal pole-signals.  The pole bases are in the same quick-replace group so you can place them manually, but I think the best solution to the upgrade planner might be for this mod to forcibly delete any ret-pole selections from any upgrade-planners.

**Comment by Scarabytes** [comment]
I think, upgrade planner will never work properly with this mod.. It's a bummer, but I can't really do anything about it within the scope of the Factorio api.
