### ISSUE TITLE
0.18 support?

### ISSUE THREAD

**Issue by nucleargen** [Scarabytes/FactorioRealisticElectricTrains#19]
new update have breaking changes in particle logic

**Comment by ccope** [comment]
Looks like this might be blocked until the next (hopefully minor) factorio update: https://forums.factorio.com/viewtopic.php?t=80255

**Comment by Maacklm** [comment]
The problem is that I have a save of 430 hours with 300+ trains ! To launch the save it took me 50 minutes and I don't have train signal anymore, electricity at some place is gone and I have to do all the replacement of the locomotives ! So, it would be cool if the creator update this mod !

**Comment by ccope** [comment]
Actually it appears the create_particle interface was added in 0.18.2, so now it should be possible to convert this addon to use that function.

**Comment by Scarabytes** [comment]
Sorry for the long hiatus, I'm currently extremely busy so it might take a few weeks until I can check this out. If anyone of you is willing to make a pull request with the update, it might be a little faster overall.

**Comment by Scarabytes** [comment]
I finally made it! Sorry it took so long.
