### ISSUE TITLE
Placing via robots does not connect circuit wires

### ISSUE THREAD

**Issue by JonasJurczok** [Scarabytes/FactorioRealisticElectricTrains#2]
### Problem:
When placing a blueprint that contains electric train poles the circuit wire connections are ignored.

### Steps to reproduce:
* place rail with poles
* connect at least two poles with red or green wire
* make blueprint
* place blueprint
* wait for bots to build the ghosts

### Expected outcome:
Poles are connected with red or green wire

### Actual outcome:
No circuit wires are placed.

This breaks train station blueprints for LTN at the moment. The alternative is to keep other power poles in the station but then there are two sets of power poles :)

I don't have time to look at the code right now but as wire placement also works for non vanilla poles it might be in this mod.

**Comment by JonasJurczok** [comment]
First: awesome mod. I really love it. I'm currently 2/3rds done with replacing every rail in my angelbobs base :D

**Comment by Scarabytes** [comment]
Thanks for the detailed report!
I'm working on fixing this for the next release.
For the time being, you can maybe enable automatic wires in the mod options.

**Comment by JonasJurczok** [comment]
I'll try that. But I'm afraid this will only connect the poles to each
other, right? I have some inserters connected to the pole and this would
still not be created.

I'll try it though :)

**Comment by JonasJurczok** [comment]
The hype is real :)
