### ISSUE TITLE
creating blueprint with SHIFT crashes the game

### ISSUE THREAD

**Issue by JonasJurczok** [Scarabytes/FactorioRealisticElectricTrains#3]
### Problem:
Quick creation of blueprints crashes the game even if there is no electric train pole involved.

### Steps to reproduce:
* take emtpy blueprint in hand
* mark anything while holding shift

### Expected outcome:
Blueprint created without confirmation dialog.

### Actual outcome:
A crash similar to https://imgur.com/a/Euwe7W7

**Comment by Scarabytes** [comment]
Fixing #2 will most likely fix this too :)

**Comment by JonasJurczok** [comment]
Awesome :)

**Comment by TheSnoozer** [comment]
Not sure if related, but sounds very similar to the issue here:

While blueprinting concrete that is unrelated to the mod I got:
```
3312.428 Error MainLoop.cpp:1035: Exception at tick 306961: Error while running event Realistic_Electric_Trains::on_player_setup_blueprint (ID 68)
__Realistic_Electric_Trains__/control.lua:285: bad argument #1 to 'pairs' (table expected, got nil)
```

not sure if I was shifting :-)
