### ISSUE TITLE
risky usage of global table.

### ISSUE THREAD

**Issue by JonasJurczok** [Scarabytes/FactorioRealisticElectricTrains#5]
### Problem
Tables stored in the `global` table are not prefixed. This can lead to conflicts with other mods.

### Possible solution
Move all global tables (`wire_for_pole`, `power_for_pole`, ...) into a mod specific namespace like `global.realeltrains` or something.

**Comment by Scarabytes** [comment]
I'm not quite sure where you got this information from, because according to https://lua-api.factorio.com/latest/Global.html each mod has its own ```global``` instance. I tested that and it is indeed not possible to access the mod's global table from elsewhere.

**Comment by JonasJurczok** [comment]
Okay, awesome. :)
