### ISSUE TITLE
UPS drop in bigger bases

### ISSUE THREAD

**Issue by JonasJurczok** [Scarabytes/FactorioRealisticElectricTrains#6]
I transformed my still small angel bob base (couple hundred active chunks) to a full electric rail network.

So far no electric locomotives are active.

UPS dropped from ~58 to ~48 with only minor additions to the base.

I'm not sure where the performance drop comes from. The code seems incredibly clean.

Could it be that rendering the poles is much more complicated and thus is a source for the drop?

**Comment by Scarabytes** [comment]
Did you check in the debug menu where the slowdown actually comes from?

In my tests I usually got significant slowdown while building the poles and almost none afterwards if no locomotives ran. The script update time then was about 0.01s.

**Comment by JonasJurczok** [comment]
I don't know enough about the debug menu yet to find specifics like that.
Can you give me a hint? I have a save from before the transition, I'll
happily do some checks.

**Comment by Scarabytes** [comment]
You can hit F5 to display the debug menu. This shows a whole bunch of data on the left, including timing for all mods. I'm interested in the update times of RET for your setup. I'm not too sure if it will actually display correctly with the amount of mods you have installed, but it's worth a try.
![grafik](https://user-images.githubusercontent.com/39307101/53323058-6f6f3e00-38dd-11e9-990e-3c965733c9e8.png)

**Comment by JonasJurczok** [comment]
Okay I just checked. The update for your mod is at a constant 0.004 so it is definitely not the issue. Maybe it's the sprite rendering but that is hidden in the mess at the top.

Whatever it is it is definitely not the mod.
